version: '2'
services:
  fabric-ca:
    build:
      context: 'membersrvc'
    ports:
      - '7054:7054'
    environment:
        - MEMBERSRVC_CA_ACA_ENABLED=true
    command: sh -c 'membersrvc start'
  vp0:
    build:
      context: 'peer'
    ports:
      - '7050:7050'
      - '7051:7051'
      - '7052:7052'
      - '7053:7053'
    environment:
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=vp0
      - CORE_PEER_PKI_ECA_PADDR=fabric-ca:7054
      - CORE_PEER_PKI_TCA_PADDR=fabric-ca:7054
      - CORE_PEER_PKI_TLSCA_PADDR=fabric-ca:7054
      - CORE_SECURITY_ENABLED=true
      - CORE_SECURITY_ENROLLID=test_vp0
      - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
    links:
      - fabric-ca
    command: sh -c 'while ! nc fabric-ca 7054; do sleep 1; done; peer node start'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
